github:
  client:
    clientId: XXXXXXXXXXXXXXXXXXXXXXXXXxx
    clientSecret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user
    
google:
  client:
    clientId: xxxx.apps.googleusercontent.com
    clientSecret: xxxxxxxxxxxxxxxx
    accessTokenUri: https://accounts.google.com/o/oauth2/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    authenticationScheme: query
    scope:
      - email
      - profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v2/userinfo

logging:
  level:
      org.springframework.security: DEBUG 

spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
